#!/bin/bash
DEVICE=$1
KEY=$2
docker run --rm -it \
    --cap-add SYS_ADMIN \
    --security-opt apparmor:unconfined \
    --device /dev/fuse \
    --device $DEVICE:/dev/bitlocker \
    bitlocker-spi-toolkit:v1 $KEY
